# Generated by Django 5.1.3 on 2024-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='inform',
        ),
        migrations.AddField(
            model_name='customuser',
            name='info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
