# Generated by Django 5.1.3 on 2024-11-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='total_date',
        ),
    ]
